import {
  GraduationCap,
  Briefcase,
  Users,
  Target,
  MessageSquareMore,
  ClipboardList,
  FolderOpen,
  Send,
  FileCheck,
  Building2,
  CheckCircle2,
  FileText,
  Clock,
  Plane,
  IdCard,
  Award,
  ClipboardCheck,
} from "lucide-react"

export const workPassIcons: Record<string, React.ComponentType<{ className?: string }>> = {
  GraduationCap,
  Briefcase,
  Users,
  Target,
  MessageSquareMore,
  ClipboardList,
  FolderOpen,
  Send,
  FileCheck,
  Building2,
  CheckCircle2,
  FileText,
  Clock,
  Plane,
  IdCard,
  Award,
  ClipboardCheck,
}
